# Generated by Django 3.2.3 on 2021-07-17 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cripto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cripto_name', models.CharField(max_length=50)),
                ('cripto_symbol', models.CharField(max_length=10)),
                ('cripto_value', models.FloatField()),
                ('cripto_supply', models.IntegerField()),
                ('cripto_creators', models.CharField(max_length=100)),
                ('cripto_description', models.TextField()),
                ('cripto_category', models.CharField(max_length=100)),
                ('cripto_date_insert', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
