# Generated by Django 3.2.3 on 2021-07-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_cripto_cripto_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cripto',
            name='cripto_published',
            field=models.BooleanField(default=False),
        ),
    ]
