# Generated by Django 3.2.3 on 2021-07-18 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_cripto_cripto_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='cripto',
            name='crito_image',
            field=models.ImageField(blank=True, upload_to='images/%d/%m/%Y/'),
        ),
        migrations.AlterField(
            model_name='cripto',
            name='cripto_date_insert',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
