# Generated by Django 3.2.3 on 2021-07-19 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coins', '0004_auto_20210718_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cripto',
            name='cripto_pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
